Feature: use the map to post a article

Background: on the Actionmap home page
  Given I am on the representatives search page
  And I fill in "address" with "San Francisco"
  And I press "search button"
  And I follow "Joseph R. Biden button"
  And I follow "Joseph R. Biden add articles"
  And I press "GitHub login"
  Given I am on the representatives search page
  And I fill in "address" with "San Francisco"
  And I press "search button"
  And I follow "Kamala D. Harris button"
  And I follow "Kamala D. Harris add articles"
  Then I should see "Choose a Representative"

Scenario: good path for adding an article
  When I select "Joseph R. Biden" from "rep_id"
  And I select "Immigration" from "issue"
  And I press "Search"
  Then I should see "Select a News Article"
  And I press "Save"
  Then I should see "No article selected"
  And I choose "selected_article_2"
  And I select "3" from "rating"
  And I press "Save"
  Then I should see "News item was successfully created."
  And I should see "Joseph R. Biden"
  Then I follow "view all"
  Then I should see "Joseph R. Biden"
  And I follow "edit 1"
  Then I should see "Edit news article"
  And I fill in "link field" with "www.google.com"
  Then I press "Save"
  Then I should see "Link is invalid. Please enter a valid url that starts with http:// or https://."
  Then I fill in "link field" with "https:/ www.google.com"
  And I press "Save"
  Then I should see "Link is invalid. Please enter a valid url that starts with http:// or https:// and that doesn't contain spaces."
  Then I fill in "title field" with "something else"
  Then I fill in "link field" with "https://www.google.com"
  Then I select "Kamala D. Harris" from "news_item_representative_id"
  Then I press "Save"
  Then I should see "News item was successfully updated."
  And I should see "Kamala D. Harris"
  And I should see "something else"
  Then I follow "view all"
  Then I should not see "something else"

Scenario: deleting article
  When I select "Joseph R. Biden" from "rep_id"
  And I select "Immigration" from "issue"
  And I press "Search"
  Then I should see "Select a News Article"
  And I choose "selected_article_2"
  And I select "3" from "rating"
  And I press "Save"
  Then I should see "News item was successfully created."
  And I should see "Joseph R. Biden"
  Then I follow "view all"
  Then I should see "Joseph R. Biden"
  And I follow "edit 1"
  Then I should see "Edit news article"
  Then I fill in "title field" with "something else"
  Then I fill in "link field" with "https://www.google.com"
  Then I press "Save"
  And I follow "view all"
  And I should see "something else"
  Then I follow "delete 1"
  Then I should see "News was successfully destroyed."
  Then I should not see "something else"

Scenario: average rating
  When I select "Joseph R. Biden" from "rep_id"
  And I select "Immigration" from "issue"
  And I press "Search"
  Then I should see "Select a News Article"
  And I choose "selected_article_2"
  And I select "3" from "rating"
  And I press "Save"
  Then I should see "News item was successfully created."
  And I should see "3.00"
  Then I follow "view all"
  And I follow "Joseph R. Biden add articles"
  When I select "Joseph R. Biden" from "rep_id"
  And I select "Immigration" from "issue"
  And I press "Search"
  Then I should see "Select a News Article"
  And I choose "selected_article_1"
  And I select "4" from "rating"
  And I press "Save"
  Then I should see "News item was successfully created."
  And I should see "4.00"
  Then I follow "view all"
  And I follow "Joseph R. Biden add articles"
  When I select "Joseph R. Biden" from "rep_id"
  And I select "Immigration" from "issue"
  And I press "Search"
  Then I should see "Select a News Article"
  And I choose "selected_article_2"
  And I select "4" from "rating"
  And I press "Save"
  Then I should see "News item was successfully created."
  And I should see "3.50"


Scenario: no articles
  When I select "Manohar Raju" from "rep_id"
  And I select "Abortion" from "issue"
  And I press "Search"
  Then I should see "No articles found."
